### ISSUE TITLE
stage->setPourDuration() doesn't works

### ISSUE THREAD

**Issue by iamrajee** [TAMS-Group/mtc_pour#5]
By changing "stage->setPourDuration(ros::Duration(4.0));" to "stage->setPourDuration(ros::Duration(16.0));"  [here](https://github.com/TAMS-Group/mtc_pour/blob/master/src/mtc_pour_tams_ur5_demo.cpp), I can't observe any difference in execution. 
Also, I had uncommented these lines
`/*for(size_t i= 0; i < robot_trajectory->getWayPointCount(); ++i)
		robot_trajectory->setWayPointDurationFromPrevious(i, waypoint_duration.toSec());
	for(size_t i= 0; i < back_trajectory.getWayPointCount(); ++i)
		back_trajectory.setWayPointDurationFromPrevious(i, waypoint_duration.toSec());*/
` [here](https://github.com/rhaschke/mtc_pour/blob/master/src/pour_into.cpp) still it doesn't works?
Any help would be appreciated! @v4hn

**Comment by v4hn** [comment]
[This line](https://github.com/rhaschke/mtc_pour/blob/master/src/pour_into.cpp#L300) appends the upward to the downward trajectory with a time_from_start offset specified by the `pour_duration` property. This logic works fine for me.

Make sure you are actually looking at the replayed trajectory with `REALTIME` time profile (instead of, e.g., 0.1seconds per waypoint) in RViz.
If you still think this is a problem, please post a snapshot of the solution trajectory in `rqt_joint_trajectory_plot`.

**Comment by iamrajee** [comment]
> [This line](https://github.com/rhaschke/mtc_pour/blob/master/src/pour_into.cpp#L300) appends the upward to the downward...

Switching to REALTIME in rviz solved issue. Thanks!

**Comment by amoyalang** [comment]
> > [This line](https://github.com/rhaschke/mtc_pour/blob/master/src/pour_into.cpp#L300) appends the upward to the downward...
> 
> Switching to REALTIME in rviz solved issue. Thanks!

Hello,please help me.my environment is ros2 humble.I also encountered this problem, how can I solve it? when I param get rviz :

![Image](https://github.com/user-attachments/assets/deb3e978-a750-4086-a1c7-8468a8aac2ef)
What is REALTIME?How can I find it?
